CREATE DATABASE IF NOT EXISTS Example;
USE Example;
CREATE TABLE IF NOT EXISTS `Example`.`Users` ( `id` INT UNSIGNED NOT NULL AUTO_INCREMENT , `name` TEXT NOT NULL, `password` TEXT NOT NULL ,  PRIMARY KEY (`id`)) ENGINE = InnoDB;