## 幫這個 workflow 取名，預設為 .yml 檔名
name: 'slim_deploy'

## 監聽 main 分支若有 push 行為就執行 jobs
## 也就是 workflow 的觸發條件，也有像是 schedule 等觸發條件
## Docs: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  push:
    branches:
    - main
## 可以有多個 jobs，原則上會平行執行，若沒有則按照順序
## job 也可以有多個 steps
jobs:
  ## 這邊 build 代表 job 的名稱
  build:
    ## 指定要運行的環境
    runs-on: debian-latest
    ## 定義真正要執行的指令
    ## name: 方便 debug，名字可以自己定義
    ## uses: 直接使用其他開發者寫好的 actions
    ## Docs: https://github.com/actions/checkout
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: init)init ssh
      run: |
          ...
    - name: A)npm install -g hexo-cli
      run: |
        npm install -g hexo-cli
    - name: B)npm install
      run: |
        npm install
    - name: C) hexo d -g
      run: |
        hexo d -g